name: integrationTest

on:
  push:
    branches: ["main"]

env:
  FIREBASE_PROJECT: testlab-demo-f6fda

jobs:
  integrationTest:
    name: integration Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "17"
          cache: gradle

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get flutter packages
        run: flutter pub get

      - name: Flutter tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --debug

      - name: Create debug and test APK
        run: |
          set -ex
          cd android
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug -Ptarget="$GITHUB_WORKSPACE/integration_test/app_test.dart"

      - uses: google-github-actions/setup-gcloud@v2
      - name: Run Firebase Test Lab Tests
        run: |
          set -ex
          echo "$INTEGRATION_TEST_GCLOUD_CONFIG" | base64 -d > ./gcloud_key_file.json
          gcloud auth activate-service-account --key-file=./gcloud_key_file.json
          gcloud --quiet config set project $FIREBASE_PROJECT
          gcloud firebase test android run \
            --type instrumentation \
            --app build/app/outputs/apk/debug/app-debug.apk \
            --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --timeout 3m
        env:
          INTEGRATION_TEST_GCLOUD_CONFIG: ${{ secrets.INTEGRATION_TEST_GCLOUD_CONFIG }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-outputs
          path: |
            build/**/outputs/**/*.apk
            build/**/outputs/**/*.aab
            build/**/outputs/**/mapping.txt
            flutter_drive.log
